### ISSUE TITLE
Support GHC 7.10.3

### ISSUE THREAD

**Issue by jtdaugherty** [travitch/dismantle#2]
We'd like to support GHC 7.10.3 with these packages. At present some known issues blocking this are:
* Use of `GHC.Generics` types that are new in `8.x`
* Use of Template Haskell API features that changed in `8.x`
* Use of `semigroups` API that is no longer imported via package dependency

**Comment by ntc2** [comment]
I assume this issue is stale; please reopen if I'm wrong.
